# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55f51b968eadf5ff4c172cb6abbb4cbf4426c910076bc9dae87949365ce74dd1bb08d6c1b06c73e46f855c2f6415ee727ddf1ead787ed5f9555faccab31088f6

test:
  secret_key_base: a13071685fab81cbec6b69c5fc2b44c9ab26313f9b5d73a56b67ccd3ad635bf0bab59396db6988d9ddaf6d3f6ba3f7a29cbbedbe574ca45bb0537d2042752917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
